title: Springboard
remote_theme: pmarsceill/just-the-docs

aux_links:
  "ğŸŒˆ Add Your Project":
    - "//github.com/javanile/springboard/edit/main/projects.list"

footer_content: "We â¤ ï¸Open Source"
